# This workflow will verify the exercises in the repository.
#
# Requires scripts:
# - bin/verify-exercises

name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    # apk has an old nu version, so alpine is used to ensure compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Use jq and nushell
        run: |
          curl -fsSL https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/fury-nushell.gpg
          echo "deb https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury.list
          sudo apt update
          sudo apt install jq nushell=0.104.1


      - name: Verify all exercises
        run: bin/verify-exercises
