# This workflow will verify the exercises in the repository.
#
# Requires scripts:
# - bin/verify-exercises

name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    # apk has an old nu version, so alpine is used to ensure compatibility
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Use nushell
        run: |
          curl -L -o nu.tar.gz https://github.com/nushell/nushell/releases/download/0.104.1/nu-0.104.1-x86_64-unknown-linux-gnu.tar.gz && \
          tar -xzf nu.tar.gz && \
          sudo mv nu-0.104.1-x86_64-unknown-linux-gnu/* /usr/bin/ && \
          rm nu.tar.gz && \
          rm -r nu-0.104.1-x86_64-unknown-linux-gnu


      - name: Verify all exercises
        run: bin/verify-exercises
