# This workflow will verify the exercises in the repository.
#
# Requires scripts:
# - bin/verify-exercises

name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    # TODO: replace with another image if required to run the tests (optional)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Use <setup tooling>
        run: |
          curl -L -o nushell.tar.gz "https://github.com/nushell/nushell/releases/download/0.107.0/nu-0.107.0-x86_64-unknown-linux-gnu.tar.gz" && \
          tar xvf nushell.tar.gz && \
          mv nu-0.107.0-x86_64-unknown-linux-gnu/nu /usr/local/bin/nu && \
          chmod +x /usr/local/bin/nu && \
          export PATH=/usr/local/bin:$PATH

      # TODO: install any dependencies (optional)
      # E.g. npm install, bundle install, etc.
      # - name: Install project dependencies
      #   run: <install dependencies>

      - name: Verify all exercises
        run: bin/verify-exercises
